### ISSUE TITLE
Error while Building Complete Sample App

### ISSUE THREAD

**Issue by proamlan** [ooyala/android-sample-apps#108]
While building complete sample app, I added following things

android {
...
    useLibrary 'org.apache.http.legacy'
}

Added this 
compile 'com.facebook.react:react-native:0.16.1'

and 
OoyalaSkinSDK.jar

to resolve compilation error.

But still com.ooyala.android.apis.ContentTreeCallback class is not found

**Comment by lental** [comment]
should be fixed now.  Some test cases may not work in the CompleteSampleApp, but it should at least compile and most cases should run.

Thanks
