### ISSUE TITLE
Exoplayer 2

### ISSUE THREAD

**Issue by tmho** [ooyala/android-sample-apps#169]
Are there any changes required to be made to support exoplayer2?

**Comment by brol1dev** [comment]
@tmho thanks for your inquire. We are currently working on supporting ExoPlayer 2. When we're done you will need to update to the latest version of our Android SDK. Unfortunately, we still don't have a release date yet but expect to hear something in the month.

**Comment by tmho** [comment]
thanks for a quick response!
