### ISSUE TITLE
"Authorization Error: invalid token" occurs when trying to launch Widevine DASH Stream

### ISSUE THREAD

**Issue by egornemov** [ooyala/android-sample-apps#204]
08-30 16:33:04.609 17156 17156 E OoyalaPlayer: This video was not authorized: Authorization Error: invalid token
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: Authorization Error: invalid token
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: com.ooyala.android.OoyalaException: Authorization Error: invalid token
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at com.ooyala.android.OoyalaPlayer.onCurrentItemChangeComplete(OoyalaPlayer.java:717)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at com.ooyala.android.OoyalaPlayer.access$200(OoyalaPlayer.java:70)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at com.ooyala.android.OoyalaPlayer$1$1.run(OoyalaPlayer.java:531)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at android.os.Handler.handleCallback(Handler.java:815)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at android.os.Handler.dispatchMessage(Handler.java:104)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at android.os.Looper.loop(Looper.java:207)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at android.app.ActivityThread.main(ActivityThread.java:5710)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
08-30 16:33:04.610 17156 17156 D com.ooyala.android.OoyalaPlayer: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
08-30 16:33:04.610 17156 17156 D PlayerInterfaceUtil: player set state ERROR, old state was INIT

**Comment by brol1dev** [comment]
To report this kind of problem we don't use the github issues. You should send this report through our incident platform http://help.ooyala.com/tech-support.

That way our Tech support will be able to troubleshoot the issue you present.
