### ISSUE TITLE
SecurePlayerSampleApp compileSdkVersion

### ISSUE THREAD

**Issue by ptaprogge** [ooyala/android-sample-apps#26]
The app/build.gridle for SecurePlayerSampleApp lists "compileSdkVersion 15", but the code uses resources from 21.

In order for the build to succeed, the line shoudl read "compileSdkVersion 21".

**Comment by jonslenkooyala** [comment]
https://github.com/ooyala/android-sample-apps/pull/27

**Comment by lental** [comment]
should be resolved

Thanks Phil,
Mike
