### ISSUE TITLE
IMA SDK version v3.8.5 will be deprecated on 5/23/2019. See the Deprecation Schedule for more details.

### ISSUE THREAD

**Issue by wezley98** [ooyala/android-sample-apps#452]
Would it be possible to upgrade the Ooyala IMA dependency used as 3.8.5 is quite old now? 

`implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.10.7'`

https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/history

**Comment by loginov-rocks** [comment]
Closing as we switched to v3.11.2 in the latest release, thanks!
