### ISSUE TITLE
Video quality has worsened since upgrading Ooyala player version

### ISSUE THREAD

**Issue by ReinisSeredzinsS** [ooyala/android-sample-apps#495]
Currently we are using ooyala version v4.32.0_RC8. After upgrading to v4.46 version we noticed that the video quality has worsened when compared to v4.32.0_RC8.  On the newest version the video quality doesn't seem to jump to the higher versions.  Ive attached  pictures that were captured between two versions of the same device. 

**v4.32_RC8**
![4 32_RC8](https://user-images.githubusercontent.com/36271576/62712280-6c32bf00-b9f2-11e9-9f66-c886fdd4605d.jpg)

**v4.46**
![4 46](https://user-images.githubusercontent.com/36271576/62712308-794fae00-b9f2-11e9-923b-331bb45efc58.jpg)

**Comment by SergeyBicarte** [comment]
@ReinisSeredzinsS , could you point asset, device (model and android version) and sample app code for reproducing?

**Comment by ReinisSeredzinsS** [comment]
@SergeyBicarte  Hi.  I have a sample app that reproduces the issue. Is there an email address that I can send it to since the video in the sample app is protected .

**Comment by SergeyBicarte** [comment]
Sure, you can try sergei.bikart@brightcove.com

**Comment by SergeyBicarte** [comment]
Hello @ReinisSeredzinsS ,
I checked that issue on your sample, it is exists and looks like it is bug in ExoPlayer libarary version 2.9.3. Our next release (4.47.0) is based on ExoPlayer 2.10.2 and I can't reproduce that bug on our candidate sample app version, on demo app from ExoPlayer git hub and on your sample with updated exoplayer and ooyalasdk libraries. You can check our candidate sample apps here https://github.com/ooyala/android-sample-apps/tree/candidate, release are planed on end of August 2019.

**Comment by ReinisSeredzinsS** [comment]
Any ETA on 4.47 release ?

**Comment by SergeyBicarte** [comment]
This week, today is very possible

**Comment by ahmed-hk95** [comment]
I confirm that the issue is still exists for me after also after upgrading to ExoPlayer to v2.10.5 and Ooyala to v4.47.0_RC9
